services:
  grafana:
    image: grafana/grafana:10.4.0
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000" # Grafana web UI
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    entrypoint:
       - sh
       - -euc
       - |
         /run.sh
    volumes:
      - ../../resources/configs/grafana-provisioning:/etc/grafana/provisioning

  


