services:
  loki:
    image: grafana/loki:latest
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ../../resources/configs/config-loki.yaml:/etc/loki/config.yaml


