services:
      
  # OpenTelemetry Collector service for receiving, processing, and exporting telemetry data
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "${OTEL_COLLECTOR_GRPC_PORT}:4317"   # OTLP gRPC receiver
      - "${OTEL_COLLECTOR_HTTP_PORT}:4318"   # OTLP HTTP receiver
      - "${OTEL_COLLECTOR_OPENCENSUS_PORT}:55681" # OpenCensus receiver (optional)
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - COLLECTOR_OTLP_ENDPOINT=http://otel-collector:4317
      - COLLECTOR_OTLP_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
