apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: LoadBalancer
  # Local Preserves the client source IP (optional for testing), other option is Cluster
  externalTrafficPolicy: Local
  selector:
    app: echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
