services:
  server:
    build:
      dockerfile: Dockerfile
      context:    ../../resources/server
    ports:
      - "8090:8090"
      
  # OpenTelemetry Collector service for receiving, processing, and exporting telemetry data
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55681:55681" # OpenCensus receiver (optional)
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - COLLECTOR_OTLP_ENDPOINT=http://otel-collector:4317
      - COLLECTOR_OTLP_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - otel
  
  # Loki service for log aggregation and storage
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki HTTP API
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ../../resources/configs/config-loki.yaml:/etc/loki/local-config.yaml
    networks:
      - otel

  # Grafana service for dashboards and visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana web UI
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ../../resources/configs/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - otel

  # Alloy agent for collecting and forwarding logs, metrics, and traces
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: ["run", "/etc/alloy/config.alloy"]
    volumes:
      - ../../resources/configs/alloy-config.alloy:/etc/alloy/config.alloy
    depends_on:
      - loki
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - otel

  prometheus:
    image: prom/prometheus:v2.45.3
    restart: unless-stopped
    volumes:
      - ../../resources/configs/prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus web UI
    networks:
      - otel
      
  portainer:
    image: portainer/portainer-ce:2.20.3
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - otel
      
# Persistent volume for Grafana data
volumes:
  grafana-data:
  portainer_data:
   
networks:
  otel: 