services:
  # Application server (Node.js example)
  server:
    extends:
      file: ../resources/compose/server.yaml
      service: server
    networks:
      - lab04

  # Loki - log aggregation system
  loki:
    extends:
      file: ../resources/compose/loki.yaml
      service: loki
    networks:
      - lab04

  # Grafana - visualization and dashboards
  grafana:
    extends:
      file: ../resources/compose/grafana.yaml
      service: grafana
    networks:
      - lab04

  # Prometheus - metrics collection and monitoring
  prometheus:
    extends:
      file: ../resources/compose/prometheus.yaml
      service: prometheus
    networks:
      - lab04

  # Node Exporter - exposes hardware and OS metrics to Prometheus
  node-exporter:
    extends:
      file: ../resources/compose/node-exporter.yaml
      service: node-exporter
    networks:
      - lab04

  # Portainer - Docker management UI
  portainer:
    extends:
      file: ../resources/compose/portainer.yaml
      service: portainer
    networks:
      - lab04

volumes:
  # Persistent storage for Portainer data
  portainer_data:

networks:
  # Network for the services to communicate
  lab04:
    driver: bridge

